from typing import Literal
from pydantic import BaseModel

entities = Literal["DOCUMENT", "SECTION", "INTRODUCTION", "OBJECTIVES", "SCOPE_OF_APPLICATION", "REQUIREMENTS", "SUBREQUIREMENTS"]
relations = Literal["HAS_SECTION", "HAS_INTRODUCTION", "HAS_OBJECTIVES", "HAS_SCOPE_OF_APPLICATION", "HAS_REQUIREMENTS", "HAS_SUBREQUIREMENTS", "NEXT"]

validation_schema = {
    "DOCUMENT": ["HAS_SECTION", "NEXT"],
    "SECTION": ["HAS_INTRODUCTION", "HAS_OBJECTIVES", "HAS_SCOPE_OF_APPLICATION", "HAS_REQUIREMENTS", "NEXT"],
    "INTRODUCTION": ["NEXT"],
    "OBJECTIVES": ["NEXT"],
    "SCOPE_OF_APPLICATION": ["NEXT"],
    "REQUIREMENTS": ["HAS_SUBREQUIREMENTS", "NEXT"],
    "SUBREQUIREMENTS": ["NEXT"],
}


class Query(BaseModel):
    query: str